name: Assign Pull Request

on:
  pull_request_target:
    types: [opened, reopened]
    branches:
      - main

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to author
        uses: peter-evans/assign-to-me@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
