name: Verify Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'
      - name: Install Dependencies
        run: npm install
      - name: Run Verification
        run: npm run verify
